name: 'Clone Any Git Repo Action'

description: "Clone any git repository in Github Actions"

inputs:
  repository:
    description: 'Repository url'
    required: true
  access_token:
    description: 'Access token with http protocol'
    required: false
  ssh_key:
    description: 'SSH private key'
    required: false
  ssh_host:
    description: 'SSH server host, will auto scan known hosts by this value'
    required: false
  target:
    description: 'Clone target dir name'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'download'
  color: 'blue'
