name: 'Smart Vercel'

description: 'Smart build and deploy to Vercel'

inputs:
  node_version:
    description: 'Nodejs version'
    required: false
    default: '14.17.0'
  script_install:
    description: 'Install dependencies script'
    required: false
    default: 'yarn install'
  script_build:
    description: 'Build project script'
    required: false
    default: 'yarn build'
  workdir:
    description: 'Workdir'
    required: false
    default: '.'
  project_name:
    description: 'The name of project in Vercel'
    required: false
  vercel_group:
    descritpion: 'Vercel group account'
    required: false
  vercel_token:
    description: 'Vercel token'
    required: true
  preview_output:
    description: 'Output preview markdown'
    required: false


runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'download'
  color: 'blue'
