name: 'Wxpusher'

description: 'Wxpusher send message'

inputs:
  token:
    description: 'wxpusher token'
    required: true
  content:
    description: 'content'
    required: true
  topic:
    description: 'topics'
    required: false
  uid:
    description: 'uids'
    required: false
  url:
    description: 'wxpusher api'
    default: 'https://wxpusher.zjiecode.com'
  verify_pay:
    description: 'verify pay'
    default: 'false'
  verify_pay_type:
    description: 'verify pay type'
    default: '0'

outputs:
  RESPONSE:
    description: "Wxpusher send message response"
    value: ${{ steps.send_message.outputs.RESPONSE }}

runs:
  using: "composite"
  steps:
    - name: Send message
      shell: bash
      id: send_message
      run: |

        INPUT_TOKEN='${{ inputs.token }}'
        INPUT_CONTENT='${{ inputs.content }}'
        INPUT_TOPIC='${{ inputs.topic }}'
        INPUT_UID='${{ inputs.uid }}'
        INPUT_URL='${{ inputs.url }}'
        INPUT_VERIFY_PAY='${{ inputs.verify_pay }}'
        INPUT_VERIFY_PAY_TYPE='${{ inputs.verify_pay_type }}'

        TOPICS=$(echo "${INPUT_TOPIC}" | sed ":a;$!N;s/\n/ /g;ba" | sed "s/ /,/g")
        UIDS=$(echo "${INPUT_UID}" | sed ":a;$!N;s/\n/ /g;ba" | sed "s/ /,/g")

        BODY=$(
        jq -n --arg appToken "$appToken" \
              --arg content "$content" \
              --arg summary "$summary" \
              --argjson contentType "$contentType" \
              --arg url "$url" \
              --argjson verifyPay "$verifyPay" \
              --argjson verifyPayType "$verifyPayType" \
              --arg topicIds "$topicIds" \
              --arg uids "$uids" \
        '{
          appToken: $appToken,
          content: $content,
          summary: $summary,
          contentType: $contentType,
          url: $url,
          verifyPay: $verifyPay, 
          verifyPayType: $verifyPayType
        }
        + (if $topicIds | length > 0 then { topicIds: ($topicIds | split(",") | map(tonumber)) } else {} end)
        + (if $uids | length > 0 then { uids: ($uids | split(",") | map(tonumber)) } else {} end)'
        )

        RESPONSE=$(
          curl -X POST --location='https://wxpusher.zjiecode.com/api/send/message' \
            --header='Content-Type: application/json' \
            --data="${BODY}"
        )

        R_SUCCESS=$(echo $RESPONSE | jq '.success')
        if [[ "success" == "${R_SUCCESS}" ]]; then
          echo "RESPONSE=${RESPONSE}" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo ${RESPONSE} | jq
        exit 1
