
name: 'Tepusher'

description: 'tepusher push message'

inputs:
  template:
    description: 'template name(path) or content'
    required: true
  vars:
    description: 'variables'
    required: false
  provider:
    description: 'notify provider {weplusbot(default), wxpusher}'
    required: true
    default: 'weplusbot'

  metapath:
    description: 'metadata files path'
    required: false
    default: '__origin__/.github'

  token:
    description: 'provider token'
    required: true
  receiver:
    description: 'receiver'
    required: false
  aters:
    description: 'aters'
    required: false

runs:
  using: "composite"
  steps:
    - name: Prepare template
      id: prepare_template
      shell: bash
      run: |
        INPUT_TEMPLATE=$(cat << EOF
        ${{ inputs.template }}
        EOF
        )

        if [[ -z "$INPUT_TEMPLATE" ]]; then
          echo 'missing template'
          exit 1
        fi

        mkdir -p _____tepusher_____
        echo '/*' > _____tepusher_____/.gitignore

        PERSIST_TEMPLATE_FILE=_____tepusher_____/template.txt
        echo '*.local.*' >> .gitignore

        if [[ "$INPUT_TEMPLATE" =~ ^https?:// ]]; then
          curl -L -o $PERSIST_TEMPLATE_FILE $INPUT_TEMPLATE
        else
          if [[ -f "$INPUT_TEMPLATE" ]]; then
              PERSIST_TEMPLATE_FILE=$INPUT_TEMPLATE;
            else
              echo "$INPUT_TEMPLATE" > $PERSIST_TEMPLATE_FILE
          fi
        fi

        echo "TEMPLATE=${PERSIST_TEMPLATE_FILE}" >> $GITHUB_OUTPUT


    - name: Get branch names.
      id: branch-names
      uses: tj-actions/branch-names@v8

    - uses: fewensa/actions/read-files@main
      id: read-files
      with:
        paths: ${{ inputs.metapath }}
        enable-segment: true
        shrink-line: true


    - name: Prepare vars
      shell: bash
      run: |
        INPUT_VARS=$(cat << EOF
        ${{ inputs.vars }}
        EOF
        )
        VARS_FILE=_____tepusher_____/vars.yml
        echo "${INPUT_VARS}" >> ${VARS_FILE}
        echo 'branch: ${{ steps.branch-names.outputs.current_branch }}' >> ${VARS_FILE}
        echo 'github_branch: ${{ steps.branch-names.outputs.current_branch }}' >> ${VARS_FILE}
        echo 'metadata: "${{ steps.read-files.outputs.content_escape }}"' >> ${VARS_FILE}
        echo 'workflows: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' >> ${VARS_FILE}



    - name: Render template
      id: render_template
      uses: chuhlomin/render-template@v1
      with:
        template: ${{ steps.prepare_template.outputs.TEMPLATE }}
        vars_path: _____tepusher_____/vars.yml

    - name: Push message
      uses: fewensa/actions/weplusbot@main
      if: ${{ inputs.provider == 'weplusbot' }}
      with:
        token: ${{ inputs.token }}
        receiver: ${{ inputs.receiver }}
        version: 'personal'
        content: ${{ steps.render_template.outputs.result }}
        template: txt
        aters: ${{ inputs.aters }}


