name: Clone Repository Workflow

on:
  push:
  workflow_dispatch:

jobs:

  clone-via-http:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          repository: fewensa/actions
          path: .github/actions

      - name: Clone repository
        uses: .github/actions/clone-any
        with:
          repository: https://github.com/fewensa/clone-any-action

      - name: Access cloned repository content
        run: |
          ls -l
